### ISSUE TITLE
info method on `annotation` raises Attribute Error

### ISSUE THREAD

**Issue by irahulsonkar** [NeuralEnsemble/libNeuroML#142]
@sanjayankur31 
Please check if  `annotation` in NeuroML2 files is handled correctly by info method.
Sample network model https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/master/CellTypesDatabase/models/NeuroML2/Network_486556811.net.nml
If above network file is loaded in `nml_doc` in python then,
`nml_doc.ion_channel[0].annotation.info(True)` raises `AttributeError: 'Annotation' object has no attribute '__ANY__'`

**Comment by sanjayankur31** [comment]
Some classes like "Annotation" can basically have any contents, so the memberspec defines them as `__ANY__`, but does not actually define a corresponding member variable for them:

```
class Annotation(BaseWithoutId):
    """Annotation -- A structured annotation containing metadata, specifically RDF or  **property**  elements"""

    __hash__ = GeneratedsSuper.__hash__
    member_data_items_ = [
        MemberSpec_(
            "__ANY__",
            "__ANY__",
            1,
            1,
            {"maxOccurs": "unbounded", "minOccurs": "0", "processContents": "skip"},
            None,
        ),
    ]
    subclass = None
    superclass = BaseWithoutId

    def __init__(self, anytypeobjs_=None, gds_collector_=None, **kwargs_):
        self.gds_collector_ = gds_collector_
        self.gds_elementtree_node_ = None
        self.original_tagname_ = None
        self.parent_object_ = kwargs_.get("parent_object_")
        self.ns_prefix_ = None
        super(globals().get("Annotation"), self).__init__(**kwargs_)
        if anytypeobjs_ is None:
            self.anytypeobjs_ = []
        else:
            self.anytypeobjs_ = anytypeobjs_

```

So, getattr throws a "AttributeError" because the `__ANY__` is not a variable in the class. As you also see from the code here, the value is merely passed on to the super class---so in your code, it'll  be passed on to `ion_channel[0]` which will have a `self.annotation` class variable either explicitly set or inherited from a super class.

So, you don't need to process annotation---you can skip it for the moment. I'll update info to ignore `__ANY__` I guess.

**Comment by irahulsonkar** [comment]
Thanks @sanjayankur31 for the details and fix.
