### ISSUE TITLE
Debug message and solution for cryptic "no attribute nsmap" error

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/libNeuroML#59]
If the lxml package is not installed, nml.py falls back on other xml parsers.  There is a hard-code reliance on the nsmap attribute, though, in a few places, which I think you don't get without lxml.  Rather than implement all the alternatives, I want to just catch these errors and encourage the user to install lxml in the debug message.  All of this would go into nml.py, but I wasn't sure how much of it is auto-generated.  Where can and can't I make lasting commits to nml.py?

**Comment by dkuhlman** [comment]
On Thu, Jan 22, 2015 at 08:06:27PM -0800, Richard C Gerkin wrote:
>    If the lxml package is not installed, nml.py falls back on other xml
>    parsers. There is a hard-code reliance on the nsmap attribute, though,
>    in a few places, which I think you don't get without lxml. Rather than
>    implement all the alternatives, I want to just catch these errors and
>    encourage the user to install lxml in the debug message. All of this
>    would go into nml.py, but I wasn't sure how much of it is
>    auto-generated. Where can and can't I make lasting commits to nml.py?

I've removed elementtree completely from generateDS.py.  Lxml is now
required both (1) when you run generateDS.py itself and (2) when you
run or import the code that it generates.

Richard, thanks for motivating me to make this change.  It's been a
long time since I've tested generateDS.py with elementtree (and
without lxml), so we really do not know what it would do.

The version containing this fix is here:
https://dkuhlman@bitbucket.org/dkuhlman/generateds

Dave


-- 

Dave Kuhlman
http://www.davekuhlman.org

**Comment by rgerkin** [comment]
@dkuhlman Awesome, thanks.
