### ISSUE TITLE
Examples missing from pypi tar (and other issues)

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#85]
The 0.2.47 tar on pypi does not include the examples folder. I don't see any changes in the Manifest.in file, though.

The readme does not mention the new releases either in the changelog at the bottom. Any chance that could be updated (and git tags used to mark these releases on github too?) This just makes it easier for us downstream to match the pypi tarball to the github source when needed---like today when I was trying to see what commit makes the 0.2.47 release---and to see what's changed between releases.

**Comment by sanjayankur31** [comment]
The Makefile for docs is also not in the tar. Could this please be included too so that the docs may be generated?

**Comment by sanjayankur31** [comment]
Ah---I just realised that the development branch is being used? Is that the default branch---or would it be merged to master when a new release is made?

**Comment by pgleeson** [comment]
Sorry @sanjayankur31, there's a pretty messy release procedure here... Basically all work is done in the development branch of libneuroml and not merged to master until there's a "full" NeuroML release (e.g. v2beta4->v2beta5) incl all the Java libraries.. However, since libNeuroML is used in a few other Python packages it's been useful to make a pypi release of the latest version... 

I'm planning to make a full nml release v soon and will merge this repo to master and make releases here etc. Also will look into making a -dev release for pip...

**Comment by sanjayankur31** [comment]
Ah, I just noticed that this is documented in the readme already. Sorry about that. I should've seen it there. Thanks very much. Closing this now.
