### ISSUE TITLE
Distribute `NML2CoreTypes` XML file along with this module

### ISSUE THREAD

**Issue by dilawar** [NeuralEnsemble/libNeuroML#88]
NeuroML2CoreTypes XML files (https://github.com/NeuroML/NeuroML2/tree/master/NeuroML2CoreTypes) should be distributed in this python module. 

The `LEMS` file often include some of these files. If the user does not provide these files along with LEMS file then the simulator should be able to find them in `neuroml` distribution.

**Comment by sanjayankur31** [comment]
This has come up in another issue here: https://github.com/NeuroML/pyNeuroML/issues/104

We need to see what the best place to distribute the XML definitions is. It could be here, or it could perhaps be pyneuroml?

**Comment by sanjayankur31** [comment]
Since pyNeuroML is the primary interface that users are meant to use to run their simulations, we've added a function there that extracts the NeuroML2CoreTypes when required by the user. So we won't ship them here

Please see this PR: https://github.com/NeuroML/pyNeuroML/pull/118

Closing this here.
